# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
  name: "gitlab-monitor"
eurekaName: "gitlab-monitor"
namespace: sequoia
owner: "PowTeam"
replicaCount: 1
image:
  pullPolicy: Always
  repository: timoschwarzer/gitlab-monitor
  tag: latest
internalPort: 80
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
config: |
  {
    "gitlabApi": "https://gitlab.com/api/v4",
    "privateToken": "ABCDEF123456",
    "maxAge": 168,
    "fetchCount": 20,
    "pipelinesOnly": false,
    "autoZoom": false,
    "showPipelineIds": true,
    "showJobs": "iconAndName",
    "showDurations": true,
    "showUsers": false,
    "projectVisibility": "any",
    "linkToFailureSound": null,
    "title": null,
    "pollingIntervalMultiplier": 10,
    "filter": {
      "include": ".*",
      "includeTags": ".*",
      "exclude": null,
      "excludeTags": null
    },
    "projectFilter": {
      "*": {
        "include": ".*",
        "exclude": null,
        "default": null,
        "showMerged": false,
        "showTags": true,
        "maxPipelines": 10,
        "notifyFailureOn": null
      }
    }
  }

