FROM ruby:2.7.0-alpine

LABEL maintainer="PowTeam"

WORKDIR /integration-tests

USER root

#install native extension packages
RUN apk update && apk add build-base mariadb-dev bash

ENV LANG="en_US.utf8"

COPY Gemfile ./

RUN bundle install && rm Gemfile.lock && rm Gemfile

COPY . ./
